baseURL: raghavmehtaportfolio.netlify.app
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A website designed by myself (Raghav) to showcase projects and hobbies.
    title: Raghav Mehta's Portfolio Website
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: rmehta.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7984584038
        title: Phone Number
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Raghav
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100013047872823
      - icon: fa-github
        label: GitHub
        url: https://github.com/Raghav-Mehta1
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/raghav-mehta-rvm

  image: ''
  name: Your name
  navigation:
    links:
      - name: About Me
        url: blogs/aliquam
      - name: CV
        url: blogs/tempus
      - name: Practical Data Analysis Case Studies
        url: blogs/ipsum
      - name: Undergraduate Dissertation
        url: blogs/magna
    menu: Menu
    subtitle: Raghav's website
    title: LBS MAM2022
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Background, Hobbies and Interests
        title: About Me
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: CV
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Investigation into Plant Networks
        title: Undergraduate Project
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Data Analysis on Biden's Election
        title: American Election Project
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Investigation into everyday working behaviour
        title: How do People work
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Goals and Future Projects
        title: Future Aspirations
        url: blogs/ipsum
  two:
    buttonText: Int
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs

markup:
  goldmark:
    renderer:
      unsafe: true
